### ISSUE TITLE
Use fixed footer

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/getnighthawk#183] opened 2021-09-23 11:37 UTC
**Desired State of the GetNighthawk.dev site**

Use fixed footer across the website so that it stays at the bottom even when the content in the page is very less.

![Screenshot 2021-09-23 at 5 05 16 PM](https://user-images.githubusercontent.com/49474499/134500246-36e69ec8-84f3-4d1f-9bd6-2b5614b0dcf6.png)

There is whitespace below the footer if it is not obvious from the screenshot.

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by warunicorn19** [comment] 2021-09-23 11:42
@navendu-pottekkat I think you mean a fixed footer right? A sticky one would travel with the page.

**Comment by navendu-pottekkat** [comment] 2021-09-23 11:46
Yes, that is what I meant. Bad with UI jargons.

**Comment by toth2000** [comment] 2021-09-23 13:20
@navendu-pottekkat can you please mention the steps to reproduce the error? The footer seems fine on my device (Chrome).

**Comment by ruhi09** [comment] 2021-09-23 13:30
Yes, this works fine for me too, even if the content is less... is the error reproduced in a specific page?? // @navendu-pottekkat

**Comment by warunicorn19** [comment] 2021-09-23 13:32
https://getnighthawk.dev/docs/section2

i think this would help. @ruhi09 @toth2000

**Comment by toth2000** [comment] 2021-09-23 13:42
Okay, I will look into it.

**Comment by warunicorn19** [comment] 2021-09-23 13:48
Huh, that's weird 🤔🤔. This is in chrome though.

**Comment by toth2000** [comment] 2021-09-23 13:57
@ruhi09 try checking different resolutions using the chrome developer tools.

**Comment by ruhi09** [comment] 2021-09-23 14:20
@toth2000 yes, it is visible only in some resolutions, I get it!

**Comment by toth2000** [comment] 2021-09-23 16:12
I looked into the issue and it is caused by the empty content. It will get fixed automatically when we add content to the empty sections. For now, it can be fixed by setting the height of the div container containing Test text to 100vh. What do you people think?

**Comment by navendu-pottekkat** [comment] 2021-09-23 16:23
If empty page is the issue, then it should not be an issue. Because I opened a PR that adds content.

**Comment by toth2000** [comment] 2021-09-23 17:39
@navendu-pottekkat I checked your PR. If the content height is not enough, the issue persists. I have created a PR to fix this.
![image](https://user-images.githubusercontent.com/65480420/134554789-559fbb5b-9f6c-48ea-8c6f-49a0e400bfbe.png)

**Closed** 2021-10-01 16:50 UTC
Labels: component/ui, good first issue
