### ISSUE TITLE
Unresponsive image

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/getnighthawk#212] opened 2021-11-22 09:23 UTC
**Description**
The image next to Layer 7 Performance is unresponsive.

**Expected Behavior**

It should be responsive on all screen sizes

**Screenshots**

https://user-images.githubusercontent.com/53532328/142835539-4e8bc286-c075-4f6b-b904-e001b14e37ba.mov

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by leecalcote** [comment] 2021-11-22 14:37
Here is an SVG version of the image that can be used to replace the PNG.
[meshery-nighthawk-deployment.svg.zip](https://github.com/layer5io/getnighthawk/files/7581944/meshery-nighthawk-deployment.svg.zip)

**Comment by The-Loony-Coder** [comment] 2021-11-22 14:47
I would like to work on this issue.

**Comment by leecalcote** [comment] 2021-11-23 01:38
Excellent 🙂

**Comment by Abusayid693** [comment] 2021-11-30 15:09
The text block  of same section is not  centre aligned for mobile view unlike other sections

**Bug (left aligned)**

![Screenshot 2021-11-30 at 8 24 06 PM](https://user-images.githubusercontent.com/35341198/144071813-fed63304-ef37-4350-9f57-5614f523f9c8.png)

**Other section (centre aligned)**

![Screenshot 2021-11-30 at 8 24 14 PM](https://user-images.githubusercontent.com/35341198/144072016-0db7a051-35c7-4a11-8878-351e50aba497.png)

**Comment by l5io** [comment] 2021-12-01 21:25
@Abusayid693 please do jump in to fix. 👍

**Comment by l5io** [comment] 2021-12-01 21:25
@The-Loony-Coder any progress to report? Any assistance needed?

**Comment by The-Loony-Coder** [comment] 2021-12-02 11:12
Hey @Abusayid693 would you like to work on this issue,I broke my screen and its taking time to get fixed up.

**Comment by Abusayid693** [comment] 2021-12-02 12:26
@The-Loony-Coder @l5io  sure I will look into it, any idea where I find Figma file for this website design

**Comment by sandeep-v1404** [comment] 2021-12-04 08:11
Can I work on this issue?

**Comment by vedant-kakde** [comment] 2021-12-04 08:14
@sandeep-v1404 Yes, go ahead 🚀

**Comment by kayceeDev** [comment] 2021-12-04 12:31
> Here is an SVG version of the image that can be used to replace the PNG. [meshery-nighthawk-deployment.svg.zip](https://github.com/layer5io/getnighthawk/files/7581944/meshery-nighthawk-deployment.svg.zip)

The image in this zip is entirely different from what is expected. @leecalcote  please can you check the zip you sent.

**Comment by Abusayid693** [comment] 2021-12-08 09:29
@sandeep-v1404 any progress on this issue..?

**Comment by kayceeDev** [comment] 2021-12-08 09:43
The issue is currently been worked on @Abusayid693  and a PR has been created regarding it #210 
@leecalcote can the SVG of the image still be generated by any chance because after going through the suggested steps in the last meeting, the pixel of the image is still affected when resizing the page?.

**Comment by adithyaakrishna** [comment] 2021-12-26 10:13
Closing this in favor of https://github.com/layer5io/getnighthawk/pull/227

**Closed by adithyaakrishna** 2021-12-26 10:13 UTC
Labels: good first issue, help wanted, kind/bug, language/html, issue/remind, area/website
