### ISSUE TITLE
[Site] Footer - misaligned

### ISSUE THREAD

**Issue by leecalcote** [layer5io/getnighthawk#84] opened 2021-03-24 22:40 UTC
**Description**

<img width="1539" alt="Screen Shot 2021-03-24 at 5 27 26 PM" src="https://user-images.githubusercontent.com/7570704/112392767-f8791f00-8cc7-11eb-87b2-40df3d0f7225.png">

**Environment:**
- Browser: Safari
---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by EmperorYP7** [comment] 2021-03-25 12:14
Couldn't reproduce this error on Safari. What's the screen-size shown in the screenshot?

**Comment by vinayaksh42** [comment] 2021-03-31 10:13
This issue has been fixed by this Pull Request - https://github.com/layer5io/getnighthawk/pull/85

**Closed by vinayaksh42** 2021-03-31 10:13 UTC
Labels: component/ui, framework/jekyll, good first issue, kind/bug
